version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - [%(filename)s] - [%(levelname)s] - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file_handler1:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../log/data_acquisition/info.log
    when: 'D'
    backupCount: 5
    encoding: utf8
  error_file_handler1:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ../log/data_acquisition/error.log
    when: 'D'
    backupCount: 5
    encoding: utf8
loggers:
  data_acquisition_logger:
    level: DEBUG
    handlers: [console, info_file_handler1, error_file_handler1,]
    propagate: no
root:
  level: INFO
  handlers: [console]